- name: Install dependencies
  apt:
    name: rsync
    state: present
  become: true

- name: Clone dotfiles repo locally.
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
    version: "{{ dotfiles_repo_version }}"
    accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"
  become: false

- name: Prepare excludes list
  set_fact:
    excludes: "{{ excludes | default([]) + ['--exclude=' ~ item] }}"
  loop: "{{ dotfiles_exclude_defaults + dotfiles_excludes }}"

- name: Sync dotfiles
  ansible.posix.synchronize:
    src: "{{ dotfiles_repo_local_destination }}/"
    dest: "{{ dotfiles_home }}"
    recursive: true
    checksum: true
    rsync_opts: "{{ dotfiles_rsync_opts + excludes }}"
  become: false

- name: Setup shell cache directory
  file:
    path: "{{ ansible_env.HOME }}/.cache/shell"
    state: directory
