- name: Clone dotfiles repo locally.
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
    version: "{{ dotfiles_repo_version }}"
    accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"
  become: false

- name: Sync dotfiles
  ansible.posix.synchronize:
    src: "{{ dotfiles_repo_local_destination }}/"
    dest: "{{ dotfiles_home }}"
  become: false
